### PR TITLE
Add ability to change help short identifier

### PR DESCRIPTION
**Pull request by DanielKag**

### CODE REVIEW

**Comment by Schniz** [comment]
this is kinda problematic because:

1. as I mentioned in the issue, `-h` is sort of a standard
2. cmd-ts works by "registering" known flags, so we probably need to make it global or have some kind of context, to pass it between the tree of subcommands

I understand the feature but I'm not sure that it provides value. Unfortunately I think your solution of manipulating `-h` to be `--headless` is the best one if you really want it. but my opinions are loosely held.

@deanshub what do you think?

**Comment by deanshub** [comment]
I really appreciate the effort ( issue + PR way to go @DanielKag 🎸  ) but if we allow this we should also allow overriding `-v` for version and I as-well don't like the overriding of standards...

**Comment by DanielKag** [comment]
We have a workaround (see in the issue) that we can use. 
Thx for sharing your thoughts

**Comment by Schniz** [comment]
great! sorry for closing 🙏 thanks for using cmd-ts

**Pull request closed without merging**
